Create Table BankData(id text Primary Key,
address_state text  ,
application_type text,
emp_length text,
emp_title text,grade text,
home_ownership text,	
issue_date DATE,
last_credit_pull_date DATE,
last_payment_date DATE,
loan_status text ,
next_payment_date Date,
member_id text,
purpose text,
sub_grade text,
term text,
verification_status text,
annual_income real ,
dti DOUBLE PRECISION ,
installment DOUBLE PRECISION ,
int_rate  DOUBLE PRECISION,
loan_amount INT ,
total_acc INT ,
total_payment INT 
)
